Modified Dockerfile to autodetect yarn or npm for builds

diff --git a/docker/node-nuxt/Dockerfile b/docker/node-nuxt/Dockerfile
--- a/docker/node-nuxt/Dockerfile
+++ b/docker/node-nuxt/Dockerfile
@@ -3,22 +3,32 @@ ARG NODE_VERSION=22
 FROM node:${NODE_VERSION}-alpine AS build
 WORKDIR /app
 
+# Enable corepack for yarn and pnpm support
 RUN corepack enable
 
-# Copy package.json and your lockfile, here we add pnpm-lock.yaml for illustration
-COPY package.json package-lock.json ./
+# Copy package.json and all possible lockfiles
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
 
-# Install dependencies
-RUN npm i
+# Install dependencies based on which lockfile exists
+RUN \
+  if [ -f yarn.lock ]; then yarn install --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then pnpm install --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
 # Copy the entire project
 COPY . ./
 
-# Build the project
-RUN npm run build
+# Build the project based on which lockfile exists
+RUN \
+  if [ -f yarn.lock ]; then yarn run build; \
+  elif [ -f package-lock.json ]; then npm run build; \
+  elif [ -f pnpm-lock.yaml ]; then pnpm run build; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
-# Build Stage 2
-
+# Production Stage
 FROM node:${NODE_VERSION}-alpine
 WORKDIR /app
 
@@ -28,7 +38,6 @@ COPY --from=build /app/.output/ ./
 # Change the port and host
 ENV PORT=8080
 ENV HOST=0.0.0.0
-
 EXPOSE 8080
 
 CMD ["node", "/app/server/index.mjs"]
